/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    pub fn foo() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn bar() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn init_context() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn create_node(
        node_name: *const ::std::os::raw::c_char,
        namespace_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn create_publisher(
        node_id: ::std::os::raw::c_int,
        topic_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn publish(
        node_id: ::std::os::raw::c_int,
        publisher_id: ::std::os::raw::c_int,
        data: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
